from typing import Any, List, TypedDict


class InvestigationStep(TypedDict, total=False):
    title: str
    why: str
    commands: List[str]
    interpretation: str


class ELSResult(TypedDict, total=False):
    """
    Deterministic ELS output computed in Python.

    This is the project-trusted layer analysis that the LLM must respect.
    """
    layer: str
    layer_number: str
    layer_name: str
    explanation: str
    next_steps: List[str]
    guided_investigation_plan: List[InvestigationStep]
    mapped_context: dict


class LearningResult(TypedDict, total=False):
    """
    Multi-lens teaching output generated by the LLM.

    These fields help the student understand the same answer through
    different professional perspectives.
    """
    kubernetes: str
    ai: str
    platform: str
    product: str


class AgentTraceStep(TypedDict, total=False):
    """
    Deterministic trace of what cka-coach did.

    We generate this in Python so the trace is stable and not invented
    by the model after the fact.
    """
    step: int
    action: str
    why: str
    outcome: str


class CoachResponse(TypedDict, total=False):
    """
    Full response object returned by ask_llm() and consumed by CLI/UI.
    """
    summary: str
    answer: str
    els: ELSResult
    learning: LearningResult
    agent_trace: List[AgentTraceStep]
    warnings: List[str]
    next_steps: List[Any]

    # Used when model parsing fails but we still want to surface the raw text.
    raw_text: str

    # Used when something failed at the Python / API layer.
    error: str
